# run mode (debug,test,release)
run_mode = "debug"

# doc directory
doc_dir = "./docs"

# root user
[root]
# user name
user_name = "admin"
# password
password = "admin"

# http configuration
[http]
# http ip address
host = "0.0.0.0"
# http port
port = 8181
# certification file for SSL
cert_file = ""
# certification key file for SSL
key_file = ""
# waiting time after http close (s)
shutdown_timeout = 30

# CORS configuration
[cors]
# enable CORS or not
enable = true
# allow origin list (* allow all origins), Access-Control-Allow-Origin
allow_origins = ["*"]
# allow methods, Access-Control-Request-Method
allow_methods = ["GET","POST","PUT","DELETE","PATCH"]
# Allow other headers except for 6 default headers, Access-Control-Expose-Headers
allow_headers = []
# allow cookie and HTTP credentials or not, Access-Control-Allow-Credentials
allow_credentials = false
# time of caching preflight request results (s)
max_age = 7200

# log configuration
[log]
# log level (1:fatal 2:error,3:warn,4:info,5:debug)
level = 5
# log format (supported format：text/json)
format = "text"
# log output (supported：stdout/stderr/file)
output = "stdout"
# log filename for "file" Log Output
output_file = "export/log/little-bee.log"

# user authentication (jwt)
[jwt_auth]
# token expired Time（Unit: second）
expired = 7200
# JWT attribute (supported: any string)
signing_key = "GINADMIN"
# JWT attribute (supported：HS512/HS384/HS512)
signing_method = "HS512"
# store type (supported: buntdb/redis)
store = "buntdb"
# buntdb path, buntdb supports to store data in file or memory (supported: [filepath]/:memory:) 
buntdb_path = "export/data/little-bee-auther.db"
# redis database number, every redis supports 16 databases (supported: 0 ~ 15)
redis_db = 1

# redis configuration
[redis]
# redis address
addr = "127.0.0.1:6379"
# redis password
password = ""

# gorm configuration
[gorm]
# debug or not (true/false)
debug = true
# database type (supported：sqlite3)
db_type = "sqlite3"
# max lifetime for a connenction (s)
max_lifetime = 7200
# max number of connections
max_open_conns = 150
# max number of connections in the idle connection pool
max_idle_conns = 50

# sqlite database configuration
[sqlite3]
# path of sqlite database
path = "export/data/little-bee-sql.db"
