# run mode (debug,test,release)
run_mode = "debug"

# Log Configuration
[log]
# Log Level (1:fatal 2:error,3:warn,4:info,5:debug)
level = 5
# Log Format (supported format：text/json)
format = "text"
# Log Output (supported：stdout/stderr/file)
output = "stdout"
# Log Filename for "file" Log Output
output_file = "data/ginadmin.log"

# User Authentication (jwt)
[jwt_auth]
# JWT Attribute (supported：HS512/HS384/HS512)
signing_method = "HS512"
# JWT Attribute (supported: any string)
signing_key = "GINADMIN"
# Token Expired Time（Unit: second）
expired = 7200

# gorm Configuration
[gorm]
# Debug or not (true/false)
debug = true
# Database Type (supported：sqlite3)
db_type = "sqlite3"
# Max lifetime for a connenction (s)
max_lifetime = 7200
# Max number of connections
max_open_conns = 150
# Max number of connections in the idle connection pool
max_idle_conns = 50

# sqlite Database Configuration
[sqlite3]
# The path of sqlite database
path = "data/ginadmin.db"

