on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        redis-version: [5.0]
        go-version: [1.13.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Sqlite
      run: sudo apt-get update && sudo apt-get install -y sqlite3
    - name: Test Env
      run: go version && redis-cli --version && sqlite3 --version
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
